"""Built-in analysis recipes."""

from analysis.recipes import (
    agent_interaction_dynamics,
    ai_review_behavior,
    code_quality_by_condition,
    control_arm_audit,
    correlation,
    fatigue_by_condition,
    mean_comparison,
    meyer_fragmentation,
    paired_nonparametric,
    paste_behavior,
    stuck_episodes,
    task_outcome_by_condition,
    tlx_debrief,
    two_group_nonparametric,
    two_proportion,
    typed_measures,
    ziegler_acceptance_rate,
)

__all__ = [
    "agent_interaction_dynamics",
    "ai_review_behavior",
    "code_quality_by_condition",
    "control_arm_audit",
    "correlation",
    "fatigue_by_condition",
    "mean_comparison",
    "meyer_fragmentation",
    "paired_nonparametric",
    "paste_behavior",
    "stuck_episodes",
    "task_outcome_by_condition",
    "tlx_debrief",
    "two_group_nonparametric",
    "two_proportion",
    "typed_measures",
    "ziegler_acceptance_rate",
]
