import { Sparkles } from "lucide-react";
import { MoveCard } from "./MoveCard";
import { RecommendationCard } from "./RecommendationCard";
import { FeedbackAffordance } from "./FeedbackAffordance";
import { cn } from "@/lib/cn";
import type { Turn } from "@/lib/types";

/** Feedback marking for a researcher turn. Optional — the
 * conversation renders it only for researcher turns that can be flagged. */
export interface TurnFeedback {
  suggested: boolean;
  marked: boolean;
  onMark: (note: string, kind: string) => void;
}

/* A single conversation turn: the prose, then any design moves and paper
 * recommendations it carries. There's no token streaming yet (the assistant
 * responds synchronously) — an entrance animation stands in, and it's gone
 * under reduce-motion with nothing lost. */
export function StreamingTurn({
  turn,
  addedRefs,
  onDecide,
  onAddPaper,
  feedback,
}: {
  turn: Turn;
  addedRefs: Set<string>;
  onDecide: (moveId: string, status: "accepted" | "rejected") => void;
  onAddPaper: (ref: string) => void;
  feedback?: TurnFeedback;
}) {
  const isPlatform = turn.role === "platform";
  return (
    <div
      className={cn(
        "flex flex-col gap-3",
        isPlatform ? "items-start" : "items-end")}
    >
      <div
        className={cn(
          "max-w-[46ch] rounded-card px-4 py-3 text-sm animate-in fade-in duration-entrance",
          isPlatform
            ? "bg-surface border border-border text-text"
            : "bg-accent text-accent-contrast")}
      >
        <span className="mb-1 flex items-center gap-1 text-xs opacity-70">
          {turn.author}
          {isPlatform && turn.source === "llm" && (
            <span
              className="inline-flex items-center gap-0.5"
              data-agent-status="llm-guided"
              title="Generated by the configured LLM provider"
            >
              <Sparkles className="size-3" aria-hidden />
            </span>
          )}
        </span>
        {turn.text}
      </div>

      {!isPlatform && feedback && (
        <FeedbackAffordance
          suggested={feedback.suggested}
          marked={feedback.marked}
          onMark={feedback.onMark}
        />
      )}

      {turn.moves.length > 0 && (
        <div className="flex w-full max-w-[46ch] flex-col gap-2">
          {turn.moves.map((m) => (
            <MoveCard key={m.moveId} move={m} onDecide={onDecide} />
          ))}
        </div>
      )}

      {turn.recommendations.length > 0 && (
        <div className="grid w-full max-w-[46ch] gap-2 sm:grid-cols-2">
          {turn.recommendations.map((r) => (
            <RecommendationCard
              key={r.ref}
              rec={r}
              added={addedRefs.has(r.ref)}
              onAdd={onAddPaper}
            />
          ))}
        </div>
      )}
    </div>
  );
}
