import { Check, CloudOff, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MoveCard } from "./MoveCard";
import { cn } from "@/lib/cn";
import type { MoveStatus, Turn } from "@/lib/types";

export function StreamingTurn({
  turn,
  onDecide,
  onAcceptBatch,
  focusMoveId = null,
  active = false,
}: {
  turn: Turn;
  onDecide: (moveId: string, status: MoveStatus, move?: Turn["moves"][number]) => void;
  onAcceptBatch?: (moves: Turn["moves"]) => void;

  focusMoveId?: string | null;

  active?: boolean;
}) {
  const isPlatform = turn.role === "platform";
  const isUnavailable = turn.source === "unavailable";
  const isScope = turn.source === "scope";
  return (
    <div
      className={cn(
        "flex min-w-0 flex-col gap-3",
        isPlatform ? "items-start" : "items-end")}
    >
      <div
        className={cn(
          "type-body animate-in fade-in duration-entrance",
          isPlatform
            ? "max-w-bubble px-1 py-1 text-text"
            : "max-w-[52ch] rounded-card border border-border bg-zone-9 px-3.5 py-2.5 text-text",

          isUnavailable && "border-dashed bg-transparent text-text-muted")}
      >
        {isPlatform && (
          <span className="mb-1 flex items-center gap-1 type-caption text-text-muted">
            {isUnavailable ? "Not answered" : isScope ? "Supported scope" : turn.author}
            {turn.source === "llm" && (
              <span
                className="inline-flex items-center gap-0.5"
                title="Generated by the configured LLM provider"
              >
                <Sparkles className="size-3" aria-hidden />
              </span>
            )}
            {isUnavailable && (
              <CloudOff
                className="size-3"
                aria-hidden
              />
            )}
          </span>
        )}
        {isPlatform && active ? (
          <ReplyParagraphs text={turn.text} />
        ) : (
          <p className="whitespace-pre-wrap">{turn.text}</p>
        )}
      </div>

      {turn.moves.length > 0 && (
        <div className="flex w-full min-w-0 max-w-decision flex-col gap-1.5">
          {onAcceptBatch && turn.moves.filter((m) => m.status === "proposed" && m.kind !== "caution").length > 1 && (
            <div className="flex items-center justify-between gap-3 rounded-card border border-accent/30 bg-accent/5 px-3 py-2">
              <p className="type-caption text-text-muted">
                These choices came from your brief. Review them individually or apply the setup together.
              </p>
              <Button
                size="sm"
                variant="subtle"
                className="shrink-0 !h-8 !px-2.5"
                onClick={() => onAcceptBatch(turn.moves.filter((m) => m.status === "proposed" && m.kind !== "caution"))}
              >
                <Check aria-hidden />
                Accept all
              </Button>
            </div>
          )}
          {turn.moves.map((m) => (
            <MoveCard
              key={m.moveId}
              move={m}
              onDecide={onDecide}

              autoFocus={m.moveId === focusMoveId}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function ReplyParagraphs({ text }: { text: string }) {
  const blocks = text
    .split(/\n{2,}/)
    .flatMap((block) => {
      const sentences = block.trim().split(/(?<=[.!?])\s+(?=[A-Z0-9“])/);
      if (sentences.length < 4) return [block.trim()];
      const chunks: string[] = [];
      for (let i = 0; i < sentences.length; i += 2) {
        chunks.push(sentences.slice(i, i + 2).join(" "));
      }
      return chunks;
    })
    .filter(Boolean);

  return (
    <div className="flex flex-col gap-2.5">
      {blocks.map((block, index) => (
        <p key={`${index}-${block.slice(0, 12)}`}>{block}</p>
      ))}
    </div>
  );
}
