import { Sparkles } from "lucide-react";
import { MoveCard } from "./MoveCard";
import { cn } from "@/lib/cn";
import type { MoveStatus, Turn } from "@/lib/types";

/* A single conversation turn: the prose, then any design moves it carries.
 * Paper recommendations live in the persistent recommender rail (one mental
 * model), not inline here. There's no token streaming yet (the assistant
 * responds synchronously) — an entrance animation stands in, and it's gone
 * under reduce-motion with nothing lost. */
export function StreamingTurn({
  turn,
  onDecide,
}: {
  turn: Turn;
  onDecide: (moveId: string, status: MoveStatus) => void;
}) {
  const isPlatform = turn.role === "platform";
  return (
    <div
      className={cn(
        "flex flex-col gap-3",
        isPlatform ? "items-start" : "items-end")}
    >
      <div
        className={cn(
          "max-w-bubble rounded-card px-4 py-3 text-sm animate-in fade-in duration-entrance",
          isPlatform
            ? "bg-surface border border-border text-text"
            : "bg-accent text-accent-contrast")}
      >
        <span className="mb-1 flex items-center gap-1 text-xs opacity-70">
          {turn.author}
          {isPlatform && turn.source === "llm" && (
            <span
              className="inline-flex items-center gap-0.5"
              data-agent-status="llm-guided"
              title="Generated by the configured LLM provider"
            >
              <Sparkles className="size-3" aria-hidden />
            </span>
          )}
        </span>
        {turn.text}
      </div>

      {turn.moves.length > 0 && (
        <div className="flex w-full max-w-bubble flex-col gap-2">
          {turn.moves.map((m) => (
            <MoveCard key={m.moveId} move={m} onDecide={onDecide} />
          ))}
        </div>
      )}
    </div>
  );
}
