"""Replication-kit export (FR-PROT-7, NFR-6; roadmap/09 item 1).

``protocol export replication-kit`` packages one study into a single
archive from which a third party reproduces the analysis:

    <studyId>-replication-kit/
      README.md          how to reproduce, exactly two commands
      protocol.yaml      the frozen protocol, verbatim bytes
      dataset.json       the anonymized one-timeline dataset export
      report/<studyId>/  the per-RQ report + recipe outputs, regenerated
                         from dataset.json at export time (so the kit is
                         born self-consistent - its report IS a
                         reproduction, not a copy of prior output)
      versions.json      kit manifest: protocol/package/recipe/schema
                         versions and the event schema versions present
      schema/            the study-protocol JSON schema
      uv.lock, .python-version   the pinned environment (D16)
      literature.json    the protocol's paper->element links (full paper
                         metadata joins with MP-10's ingest)

Determinism (NFR-6): the archive is byte-stable - fixed tar metadata
(mtime/uid/gid), sorted entries, gzip mtime=0 - and the report is
regenerated with ``SOURCE_DATE_EPOCH=0`` so matplotlib embeds no wall-clock
dates. Exporting the same protocol + dataset twice yields identical bytes;
re-running the analysis from the kit's dataset yields a byte-identical
``report.md`` (the FR-PROT-7 reproduction test).

The report is regenerated by invoking the ``analysis`` CLI as a
subprocess - the same command a replicator runs - rather than importing the
analysis package: protocol is a lower layer and must not depend on it.
"""

from __future__ import annotations

import gzip
import io
import json
import os
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
from importlib import metadata, resources
from pathlib import Path

from protocol.errors import ProtocolError
from protocol.loader import load_protocol

#: Bump when the kit layout changes; replicators branch on it (NFR-4).
KIT_FORMAT_VERSION = 1

README_TEMPLATE = """\
# Replication kit - {study_id}

Produced by `protocol export replication-kit` (FR-PROT-7). Reproduces the
study's per-RQ analysis report from the frozen protocol and the anonymized
dataset alone.

## Reproduce

From a fresh checkout of the framework repository (the pinned environment
is this kit's `uv.lock` + `.python-version`; see `versions.json` for the
package and recipe versions in force):

```bash
uv sync --all-packages
SOURCE_DATE_EPOCH=0 uv run analysis run <kit>/protocol.yaml \\
  --dataset <kit>/dataset.json --out <fresh-dir>
diff <fresh-dir>/{study_id}/report.md <kit>/report/{study_id}/report.md
```

The diff is empty: `report.md` regenerates byte-for-byte (NFR-6).
`SOURCE_DATE_EPOCH=0` keeps figure files date-free so they too are
byte-stable. An `analysis run` exit code of 2 means the report was written
but some plan entries failed requirements validation - those failures are
part of the study record and appear in the report's validation section.

## Contents

See the module docstring of `protocol/src/protocol/export.py` (this kit's
generator) for the full layout, and `versions.json` for provenance.
"""


def fetch_dataset(server: str, study_id: str) -> dict:
    """Pull the one-timeline dataset export from a running middleware."""
    url = f"{server.rstrip('/')}/studies/{study_id}/dataset?format=json"
    try:
        with urllib.request.urlopen(url, timeout=30) as res:
            return json.loads(res.read())
    except OSError as exc:
        raise ProtocolError(
            f"could not fetch dataset for {study_id!r} from {server}: {exc}; "
            "is the middleware running, or pass --dataset <export.json>"
        ) from exc


def _canonical(doc: object) -> bytes:
    text = json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False)
    return (text + "\n").encode()


def _recipe_registry() -> list[dict]:
    """The recipe registry, from the analysis CLI (subprocess, see module
    docstring for why not an import)."""
    proc = subprocess.run(
        [sys.executable, "-m", "analysis.cli", "list", "--json"],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        raise ProtocolError(
            "could not enumerate recipes via `analysis list --json` "
            f"(exit {proc.returncode}): {proc.stderr.strip()}"
        )
    return json.loads(proc.stdout)


def _regenerate_report(protocol_path: Path, dataset_path: Path, out_dir: Path) -> None:
    """Run the plan from the packaged dataset; the kit ships this output."""
    env = {**os.environ, "SOURCE_DATE_EPOCH": "0"}
    proc = subprocess.run(
        [
            sys.executable, "-m", "analysis.cli", "run",
            str(protocol_path), "--dataset", str(dataset_path),
            "--out", str(out_dir),
        ],
        capture_output=True, text=True, check=False, env=env,
    )
    # 2 = report written with loud validation failures - part of the record.
    if proc.returncode not in (0, 2):
        raise ProtocolError(
            f"analysis run failed (exit {proc.returncode}): "
            f"{proc.stderr.strip() or proc.stdout.strip()}"
        )


def _package_versions() -> dict[str, str]:
    out = {}
    for pkg in ("protocol", "analysis", "pandas", "scipy", "matplotlib"):
        try:
            out[pkg] = metadata.version(pkg)
        except metadata.PackageNotFoundError:  # pragma: no cover
            out[pkg] = "unknown"
    return out


def build_kit(
    protocol_path: Path,
    dataset: dict,
    out_path: Path,
    repo_root: Path,
) -> Path:
    """Assemble the deterministic kit archive; returns ``out_path``."""
    protocol = load_protocol(protocol_path)  # validates before packaging
    study_id = protocol["study"]["id"]
    root = f"{study_id}-replication-kit"

    with tempfile.TemporaryDirectory() as td:
        staging = Path(td)
        (staging / "protocol.yaml").write_bytes(Path(protocol_path).read_bytes())
        (staging / "dataset.json").write_bytes(_canonical(dataset))
        (staging / "README.md").write_text(
            README_TEMPLATE.format(study_id=study_id)
        )
        (staging / "literature.json").write_bytes(
            _canonical(protocol.get("literature", []))
        )

        schema_dir = staging / "schema"
        schema_dir.mkdir()
        schema_text = (
            resources.files("protocol")
            .joinpath("schema/study-protocol.schema.json")
            .read_text("utf-8")
        )
        (schema_dir / "study-protocol.schema.json").write_text(schema_text)

        for pin in ("uv.lock", ".python-version"):
            src = repo_root / pin
            if not src.is_file():
                raise ProtocolError(f"pinned environment file missing: {src}")
            (staging / pin).write_bytes(src.read_bytes())

        _regenerate_report(
            staging / "protocol.yaml", staging / "dataset.json", staging / "report"
        )

        rows = dataset.get("rows", [])
        (staging / "versions.json").write_bytes(_canonical({
            "kitFormatVersion": KIT_FORMAT_VERSION,
            "studyId": study_id,
            "protocolVersion": protocol["protocolVersion"],
            "pythonVersion": (repo_root / ".python-version").read_text().strip(),
            "packages": _package_versions(),
            "recipes": _recipe_registry(),
            "eventSchemaVersions": sorted(
                {r["v"] for r in rows if isinstance(r.get("v"), int)}
            ),
            "datasetRows": len(rows),
        }))

        # Deterministic archive: sorted members, zeroed metadata, gzip mtime=0.
        out_path.parent.mkdir(parents=True, exist_ok=True)
        buf = io.BytesIO()
        with tarfile.open(mode="w", fileobj=buf) as tar:
            for path in sorted(staging.rglob("*")):
                info = tar.gettarinfo(
                    path, arcname=f"{root}/{path.relative_to(staging).as_posix()}"
                )
                info.mtime = 0
                info.uid = info.gid = 0
                info.uname = info.gname = ""
                info.mode = 0o755 if path.is_dir() else 0o644
                if path.is_file():
                    with path.open("rb") as f:
                        tar.addfile(info, f)
                else:
                    tar.addfile(info)
        out_path.write_bytes(gzip.compress(buf.getvalue(), mtime=0))
    return out_path
